[project]
name = "Approval.Tests"
version = "0.1.0"
labview-version = "2026" #version used in development?
description = "Approval Testing Package for LabVIEW"
authors = ["Sam Taggart and Llewellyn Falco, plus other contributors"]
license = "MIT"
repository = "https://github.com/approvals/ApprovalTests.LabVIEW"

[build.package]
type = "vipb"
path = "Approval Tests.vipb"
version = "3.0.0"
