#! /usr/bin/python
#checks for [#xx] where xx is an issue number

import sys
import re
 
with open(sys.argv[1]) as f:
    first_line=f.readline()

if not re.search(r'^\[\#[0-9]+\]\s',first_line):
    print('Commit Rejected. No issue number found. Add [#nn] to front of commit message. To bypass use --no-verify') 
    sys.exit(1) # reject commit
else:
    sys.exit(0)

