name: CI - Test&Build
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # keeps GitHub from removing runner due to inactivity
jobs:
  test:
    runs-on: LV20x64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Run Unit Tests
        shell: bash
        run: ./scripts/run_unittests.sh
      - name: Build Package
        shell: bash
        run: ./scripts/build.sh $GITHUB_RUN_NUMBER  
      - name: Install 
        shell: bash
        run: ./scripts/install.sh 
      - name: Create Install Tests
        shell: bash
        run: ./scripts/create_install_tests.sh
      - name: Rerun Tests on Installed Libraries 
        shell: bash
        run: ./scripts/run_install_tests.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'reports/*.xml'
      - name: Grab Artifacts
        if: success() || failure() # always run even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: artifacts 
          path: |
            build/*.vip
            reports
