name: CI - Test&Build - Docker
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # keeps GitHub from removing runner due to inactivity
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nationalinstruments/labview:latest-linux
      options: --user root
    env:
      VIPM_SERIAL_NUMBER: ${{ secrets.VIPM_SERIAL_NUMBER }}
      VIPM_FULL_NAME: ${{ secrets.VIPM_FULL_NAME }}
      VIPM_EMAIL: ${{ secrets.VIPM_EMAIL }}
    steps: 
      - name: Install Git
        run: |
          apt-get update && apt-get install -y git
          git --version
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install VIPM
        run: |
          apt-get update && apt install wget
          wget -O /tmp/vipm.deb https://packages.jki.net/vipm/preview/vipm_latest_preview_amd64.deb
          dpkg -i /tmp/vipm.deb
          rm /tmp/vipm.deb

      - name: Activate VIPM
        run: |
          vipm activate \
            --serial-number "${{ secrets.VIPM_SERIAL_NUMBER }}" \
            --name "${{ secrets.VIPM_FULL_NAME }}" \
            --email "${{ secrets.VIPM_EMAIL }}"
      - name: Check activation
        run: vipm about

      - name: Refresh package list
        run: vipm package-list-refresh

      - name: Install project dependencies
        run: vipm install project.vipc

      - name: List installed packages
        run: vipm list --installed
      - name: Run Unit Tests
        shell: bash
        run: ./scripts/run_unittests.sh
      - name: Build Package
        shell: bash
        run: ./scripts/build.sh $GITHUB_RUN_NUMBER  
      - name: Install 
        shell: bashvipm
        run: ./scripts/install.sh 
      - name: Create Install Tests
        shell: bash
        run: ./scripts/create_install_tests.sh
      - name: Rerun Tests on Installed Libraries 
        shell: bash
        run: ./scripts/run_install_tests.sh
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'reports/*.xml'
      - name: Grab Artifacts
        if: success() || failure() # always run even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: artifacts 
          path: |
            build/*.vip
            reports
